# Generated by Django 6.0.3 on 2026-04-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0003_bouquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
