# Generated by Django 6.0.4 on 2026-04-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Pending', max_length=30),
        ),
    ]
